name: Azure App Service - filereceivertgbot(Production), Build and deploy DotnetCore app
env:
  DOTNET_ROOT: "."

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
  
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/filereceiver

    #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/filereceiver/appsettings.json'
      env:
        BotSettings.Token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ConnectionStrings.FileReceiverDb: ${{ secrets.FILE_RECEIVER_TEST_DB }}
        MegaClient.ApplicationKey: ${{ secrets.MEGA_API_KEY }}
        MegaClient.Login: ${{ secrets.MEGA_LOGIN }}
        MegaClient.Password: ${{ secrets.MEGA_PASSWORD }}
        Serilog.WriteTo[1].Args.DatabaseUrl: ${{ secrets.MONGO_CONNECTION_STRING }}
        Serilog.WriteTo[2].Args.Token: ${{ secrets.TELEGRAM_LOG_BOT_TOKEN }}
        Serilog.WriteTo[2].Args.ChatId: ${{ secrets.TELEGRAM_LOGS_CHAT_ID }}

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: filereceivertgbot
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_92CCA54CE7D6497D841104EE763EF0C7 }}
        package: ${{env.DOTNET_ROOT}}/filereceiver

